### ISSUE TITLE
Should `__init__.py` files be ignored?

### ISSUE THREAD

**Issue by ghellwig** [desy-cms/analysis#22]
I was wondering if we should add `__init__.py` files to `.gitignore` because they are auto-generated by SCRAM. I just stumbled upon this because in the `Tools` package it has not been added, but in the `Ntuplizer` it is added.

I would therefore propose to remove it in the `Ntuplizer` package and add an entry to `.gitignore`. Do others agree?

Cheers,
Gregor

**Comment by robervalwalsh** [comment]
Hi Gregor,

I agree. I may have put it there by mistake. Please go ahead.

Cheers
Roberval

**Comment by ghellwig** [comment]
Just merged PR #23  to fix this.
